[package]
edition = "2021"
name = "cruise"
version = "0.1.0"

[dependencies]
anyhow = "1"
async-std = "1.13"
bevy = "0.15"
bevy-inspector-egui = "0.29"
derivative = "2.2.0"
fastrand = "2.3"
itertools = "0.14"
reqwest = "0.12.12"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
